seed: 1337

dataset:
  root: datasets/converted_full_multiclass
  train_txt: datasets/converted_full_multiclass/train.txt
  val_txt: datasets/converted_full_multiclass/val.txt
  test_txt: datasets/converted_full_multiclass/test.txt

model:
  name: unetplusplus
  architecture: UnetPlusPlus
  encoder_name: efficientnet-b3
  encoder_weights: null
  in_channels: 3
  classes: 3
  input_size: 768
  deep_supervision: true
  init_from_checkpoint: null
  init_ignore_mismatched: true

loss:
  ce_class_weights:
    - 0.2
    - 1.0
    - 2.5
  ce_coef: 0.3
  dice_coef: 0.7

augment:
  rotate90: true
  hflip: true
  vflip: true
  brightness_contrast: true
  gamma: true

scheduler:
  type: reduce_on_plateau
  monitor: mean_dice_fg
  mode: max
  factor: 0.7
  patience: 10
  min_lr: 0.00002

early_stopping:
  monitor: mean_dice_fg
  mode: max
  patience: 25

postprocess:
  enabled: false
  leaflet:
    min_area: 0
    keep_largest: 0
    fill_holes: false
    closing_radius: 0
  fibrous_ring:
    min_area: 0
    keep_largest: 0
    fill_holes: false
    closing_radius: 0

tta:
  enabled: true
  variants:
    - orig
    - hflip
    - vflip
    - rot90
  apply_postprocess: true

train:
  save_dir: training/runs/unetpp_effb3_a100_multiclass_deepsup
  epochs: 100
  batch_size: 16
  lr: 0.0002
  weight_decay: 0.00001
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  amp: true
  cudnn_benchmark: true
  tensorboard: true
  log_every: 10
  dry_run_steps: 2
